version: '3.1'
services:
  app:
    container_name: recommender-restapi
    image: recommender-restapi
    build: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bestseller-db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bestseller-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/ # persist data even
volumes:
  pgdata:

